// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnkfbaLq9wlqb3bxfXzfDVasega7WrITk',
    appId: '1:907267211004:web:3f0142ebc2dd5349b6a179',
    messagingSenderId: '907267211004',
    projectId: 'synctours-1912b',
    authDomain: 'synctours-1912b.firebaseapp.com',
    storageBucket: 'synctours-1912b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfh11T9NM2qrHUE0HTapoWVRY3aOK7I0E',
    appId: '1:907267211004:android:77b827da321f72aeb6a179',
    messagingSenderId: '907267211004',
    projectId: 'synctours-1912b',
    storageBucket: 'synctours-1912b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6TgWI4wxHhH0oFjhStYam0RNZJv7JNZk',
    appId: '1:907267211004:ios:b8ace7b72311c4d4b6a179',
    messagingSenderId: '907267211004',
    projectId: 'synctours-1912b',
    storageBucket: 'synctours-1912b.appspot.com',
    iosBundleId: 'com.example.synctours',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6TgWI4wxHhH0oFjhStYam0RNZJv7JNZk',
    appId: '1:907267211004:ios:b8ace7b72311c4d4b6a179',
    messagingSenderId: '907267211004',
    projectId: 'synctours-1912b',
    storageBucket: 'synctours-1912b.appspot.com',
    iosBundleId: 'com.example.synctours',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnkfbaLq9wlqb3bxfXzfDVasega7WrITk',
    appId: '1:907267211004:web:03b7e472991bea1cb6a179',
    messagingSenderId: '907267211004',
    projectId: 'synctours-1912b',
    authDomain: 'synctours-1912b.firebaseapp.com',
    storageBucket: 'synctours-1912b.appspot.com',
  );
}
