List<String> getDestinationNames() {
  return [
    'Nairobi',
    'Maasai Mara',
    'Mombasa',
    'Mount Kenya',
    'Nairobi National Park',
    'Diani Beach',
    'Amboseli National Park',
    'Tsavo National Park',
    'Lake Nakuru',
    'Lamu',
    'Malindi',
    'Samburu National Reserve',
    'Hell\'s Gate National Park',
    'Aberdare National Park',
    'Chyulu Hills National Park',
    'Mount Longonot',
    'Ol Pejeta Conservancy',
    'Shimba Hills National Reserve',
    'Kisite-Mpunguti Marine National Park',
    'Watamu',
    'Kakamega Forest',
    'Meru National Park',
    'Lake Turkana',
    'Thomson\'s Falls',
    'Lake Victoria',
    'Great Rift Valley',
    'Nairobi Railway Museum',
    'Karen Blixen Museum',
    'Giraffe Centre',
    'Mida Creek',
    'Arabuko Sokoke Forest',
    'Fort Jesus',
  ];
}
